### PR TITLE
Removed pinning of wheel

### PR DESCRIPTION
**Pull request by radarhere**
Attempt to address https://github.com/matthew-brett/multibuild/pull/203

### CODE REVIEW

**Comment by hmaarrfk** [comment]
The issue is that now dask requires numpy 1.13... so if we want to test with older number, we need to find the appropriate dask version.

**Comment by hmaarrfk** [comment]
Need to stick to 1.1.5
https://github.com/dask/dask/blob/1.1.5/setup.py

**Comment by radarhere** [comment]
Hi. Sorry, I'm not following. What does this issue about auditwheel and multibuild have to do with numpy?

**Comment by hmaarrfk** [comment]
It itself has nothing with to do with numpy, but your builds aren't passing because we are forcing numpy 1.11 to be installed, but newly released dask requires a newer version....

**Comment by hmaarrfk** [comment]
Seems to be working now :/ I think it is because after you submitted the original PR, we removed dask from the list of core requirements from the library.

https://github.com/scikit-image/scikit-image/blob/v0.14.x/requirements/default.txt

**Pull request merged**
