### PR TITLE
Prefer binary wheels during pip install, even if older

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by soupault** [comment]
Why is this recommended?

**Comment by stefanv** [comment]
This is to handle the situation where Matplotlib (or other dependency) drops a version of Python before we do.

**Comment by stefanv** [comment]
Did this PR actually work? I wasn't so sure :/

**Comment by hmaarrfk** [comment]
it should work... 

but why don't you cherry-pick 
https://github.com/scikit-image/scikit-image-wheels/pull/14/files

**Comment by hmaarrfk** [comment]
I think this is the wrong approach. The correct approach seems to add things to the "pip flags" in config.sh. 

That is done in the PR
https://github.com/scikit-image/scikit-image-wheels/pull/16

**Pull request closed without merging**
