### PR TITLE
Trigger build

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jni, pretty sure this will pass now. hopefully,

**Comment by jni** [comment]
Looking good so far...!

**Comment by jni** [comment]
Boom!

**Comment by hmaarrfk** [comment]
what now?

**Comment by jni** [comment]
https://github.com/scikit-image/scikit-image/blob/master/RELEASE.txt =)

**Comment by hmaarrfk** [comment]
i guess i could make the tag, but the rest of the stuff I don't have permissions for
https://github.com/scikit-image/scikit-image/blob/master/RELEASE.txt#L66

**Comment by jni** [comment]
@hmaarrfk great point! Apologies for my too-fast skimming of that process. We have a history of forgetting the permissions issue; @soupault ran into this also I believe. :joy: you already had permissions for the repos, and I just added you to PyPI. =)

**Comment by jni** [comment]
Oh and btw, I've twice had issues with wheel-uploader being unable to find the wheels for some reason. In those cases, I have used wget in a for-loop to download all the wheels manually. Then you can use twine-upload *.wheel. 

Also, *never* push the source dist until you've verified that the wheels have been uploaded!

**Pull request merged**
