### PR TITLE
build 0.14.3 in build and monitor

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jni success!!! I think scipy probably released with a newer version of numpy!!!!

**Comment by hmaarrfk** [comment]
https://github.com/scipy/scipy/blob/master/setup.py#L434

**Comment by hmaarrfk** [comment]
@jni 

is download the docs repo suppose to take so long?


```
Receiving objects:  32% (56144/174384), 463.61 MiB | 248.00 KiB/s   
```
....

**Comment by jni** [comment]
@hmaarrfk that's a good question about the docs... That seems huge! Maybe do `--clone-depth 1` or similar? @stefanv thoughts?

**Comment by jni** [comment]
Also I'm confused about your "success" comment above... =P

**Comment by stefanv** [comment]
Yeah, that's what you get for storing the entire history. We may want to rewrite the history periodically.  For NumPy, we rewrite the website, e.g., on each upload (remove all but the last commit).  It's a bit trickier for the docs, since you also have to snapshot the previous versions that are in there, but not too difficult to do.

For NumPy, I wrote this upload script: https://github.com/xd-con/imagexd-2019/blob/master/push_dir_to_repo.py (sorry for the weird URL, I don't even know where the canonical version lives!)

**Comment by hmaarrfk** [comment]
I'd like to think that I successfully predicted a roadblock would happen.

**Pull request merged**
