### PR TITLE
Removing python 3.5 builds

### PR DESCRIPTION
**Pull request by NelleV**

### CODE REVIEW

**Comment by jni** [comment]
@NelleV you should also update the tag I think?

**Comment by NelleV** [comment]
That's already done in the branch v0.16.x

**Comment by hmaarrfk** [comment]
Can the .16 branch get deleted? Conda forge is a rolling release distro and branches should be the exception, not the norm.

In particular, the .14 branch is created so that we can continue to build the LTS while building the newer version.

**Comment by hmaarrfk** [comment]
Oops, I read the wrong repo

**Comment by soupault** [comment]
@alexdesiqueira there is something wrong with multiotsu on 32bit platforms (see the CI builds).

**Comment by NelleV** [comment]
I believe we've fixed the problem with the failing tests on 32bits.

**Comment by jni** [comment]
Yes I fixed the multi otsu test in this commit:

https://github.com/scikit-image/scikit-image/commit/c1f86496f4da226af51fc9070bf3770d863ac299

Assuming 0.16 builds properly with that, I’ll submit a PR to matter with the fix. But I’ll wait till all necessary fixes are in, in case there’s any more.

**Pull request merged**
