### PR TITLE
[Demo] No submodules

### PR DESCRIPTION
**Pull request by hmaarrfk**
I think there was some discussion on how to use CIs to automatically build things without relying on the little understood feature of git submodules.

This is simply an attempt and a demo

### CODE REVIEW

**Comment by soupault** [comment]
Looks good so far.

**Comment by jni** [comment]
I'm into this. @stefanv?

**Comment by stefanv** [comment]
I don't share the concern with submodules neither know why they are misunderstood. Can you help me understand?

**Comment by jni** [comment]
@stefanv I guess the main problem is that they are very rarely used, so most people (this includes people with extensive FOSS experience such as Mark and I) don't know how to deal with them. I had to rediscover `git submodule --init` (or is that `init`?) to make #39, then the fact that you have to go down into the submodule directory to grab the latest... And that, as far as I can tell, there's no way to tell git "grab the latest master here, always", as opposed to a specific commit...

To me, working with git submodules feels like installing packages by manually running lines from setup.py in a Python prompt. Having the dependencies in a standard text file feels much nicer, and friendlier to newcomers.

**Comment by stefanv** [comment]
I'm fine with that change, except that now we no longer have a notion of which version of that package is used to build with. If the answer is "always the latest", then we're good just cloning.

**Comment by hmaarrfk** [comment]
You can select a specific branch if you don't like master.

**Comment by stefanv** [comment]
My point was that with a submodule you can choose to stick to a specific commit.  But, I think in this case, master is almost always what we want.

**Comment by stefanv** [comment]
I think this is actually fine to merge.

**Comment by stefanv** [comment]
Presumed you would rename, but OK :)

**Comment by jni** [comment]
Thank you @hmaarrfk! This makes me very happy. =D

**Pull request merged**
