### PR TITLE
Update multibuild to latest version

### PR DESCRIPTION
**Pull request by jni**
pip 20 has broken the builds, multibuild needs to be updated. See https://mail.python.org/pipermail/numpy-discussion/2020-January/080356.html

### CODE REVIEW

**Comment by jni** [comment]
CC @stefanv

**Comment by hmaarrfk** [comment]
Is Travis expected to stay broken?

**Comment by stefanv** [comment]
Looks like we are using pip incorrectly, according to pip.

**Comment by hmaarrfk** [comment]
@jni, i find submodules really hard to work with. For one, I can never understand what branch is being used.

What do you think about https://github.com/scikit-image/scikit-image-wheels/pull/35 ??

**Comment by jni** [comment]
Closed in favour of #35 with updates. Thank you @hmaarrfk!

**Pull request closed without merging**
